[package]
name = "sp_box"
version = "0.1.0"
authors = ["clayton-andrade <clayton.andrade2009@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
